remote-theme: 
title: Anastasis1175's homepage
description: Bookmark this to keep an eye on my project updates!
defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      image: /preview.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Anastasis1175" # Replace with default author name
      image: /preview.jpg
  -
social_links:
  - name: Youtube
    url: https://youtube.com/@wowthefurry
    icon: youtube
  - name: GitHub
    url: https://github.com/Anastasis1175
    icon: github
  - name: WordPress
    url: https://aivp3.wordpress.com
paginate: 9
paginate_path: "/page:num/"
collections:
			chapters:
				output: true
				permalink: /:name/
				section: Web
				order: 1
home: "/index.html"
